const Map<String, List<String>> angolaTowns = {
  "Bengo": [
    "Ambriz",
    "Dande",
    "Nambuangongo",
    "Pango Aluquém",
    "Dembos",
    "Bula Atumba",
  ],
  "Benguela": [
    "Benguela",
    "Lobito",
    "Catumbela",
    "Cubal",
    "Baía Farta",
    "Balombo",
    "Ganda",
    "Chongoroi",
  ],
  "Bié": [
    "Kuito",
    "Camacupa",
    "Catabola",
    "Andulo",
    "Chinguar",
    "Cuemba",
    "Nharea",
    "Chitembo",
  ],
  "Cabinda": ["Cabinda", "Cacongo", "Buco Zau", "Belize"],
  "Cuando Cubango": [
    "Menongue",
    "Cuchi",
    "Cuito Cuanavale",
    "Dirico",
    "Mavinga",
    "Nancova",
    "Rivungo",
    "Calai",
  ],
  "Cuanza Norte": [
    "Ndalatando",
    "Lucala",
    "Cambambe",
    "Banga",
    "Bolongongo",
    "Golungo Alto",
    "Gonguembo",
    "Quiculungo",
    "Ambaca",
    "Samba Cajú",
  ],
  "Cuanza Sul": [
    "Sumbe",
    "Porto Amboim",
    "Cela",
    "Cassongue",
    "Conda",
    "Ebo",
    "Libolo",
    "Mussende",
    "Quibala",
    "Seles",
    "Waku Kungo",
  ],
  "Cunene": [
    "Ondjiva",
    "Cahama",
    "Cuanhama",
    "Cuvelai",
    "Namacunde",
    "Ombadja",
  ],
  "Huambo": [
    "Huambo",
    "Caála",
    "Bailundo",
    "Ecunha",
    "Longonjo",
    "Londuimbali",
    "Mungo",
    "Chicala-Cholohanga",
    "Catchiungo",
    "Ucuma",
  ],
  "Huíla": [
    "Lubango",
    "Matala",
    "Humpata",
    "Chibia",
    "Cacula",
    "Quilengues",
    "Cuvango",
    "Chipindo",
    "Jamba",
    "Caluquembe",
    "Chiange",
  ],
  "Luanda": [
    "Luanda",
    "Belas",
    "Cacuaco",
    "Cazenga",
    "Ícolo e Bengo",
    "Kissama",
    "Quilamba Quiaxi",
    "Talatona",
    "Viana",
  ],
  "Lunda Norte": [
    "Dundo",
    "Cambulo",
    "Capenda-Camulemba",
    "Chitato",
    "Caungula",
    "Lubalo",
    "Cuango",
    "Xá-Muteba",
  ],
  "Lunda Sul": ["Saurimo", "Cacolo", "Muconda", "Dala"],
  "Malanje": [
    "Malanje",
    "Cangandala",
    "Cacuso",
    "Calandula",
    "Massango",
    "Marimba",
    "Quela",
    "Quirima",
    "Kiwaba Nzoji",
    "Cambundi-Catembo",
    "Luquembo",
  ],
  "Moxico": [
    "Luena",
    "Camanongue",
    "Léua",
    "Luchazes",
    "Alto Zambeze",
    "Bundas",
    "Luacano",
  ],
  "Namibe": ["Moçâmedes", "Bibala", "Camucuio", "Virei", "Tômbua"],
  "Uíge": [
    "Uíge",
    "Negage",
    "Cangola",
    "Songo",
    "Damba",
    "Maquela do Zombo",
    "Mucaba",
    "Milunga",
    "Bembe",
    "Buengas",
    "Puri",
    "Ambuíla",
    "Quimbele",
    "Sanza Pombo",
  ],
  "Zaire": ["Mbanza Kongo", "Soyo", "Cuimba", "Noqui", "Nzeto", "Tomboco"],
};
